<div>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <img border="0" src="http://www.asthmamd.org/images/icon_user_1.png" width="90" height="50">
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="dropdown" class="active">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Profile
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'preview'));?>?id=<?php echo $this->result['id']; ?>"><span class="glyphicon glyphicon-edit"> Edit Profile</span> </a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'test'));?>"><span class="glyphicon glyphicon-check"> View Profile </span></a></li>
                        </ul>
                    </li>
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">Contact Details</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=""><?php  echo " Hello, ".$this->result; ?></a></li>
                    <li class="dropdown" class="active">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-cog"> Setting<span class="caret"></span></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'logout'));?>"><span class="glyphicon glyphicon-log-out"> Logout </span></a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'change-password'));?>"><span class="glyphicon glyphicon-edit"> Change Password</span></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div>
    <img src="http://www.web.pk/wp-content/uploads/2014/01/Public_Wifi_Security-660x300.jpg">

    <?php echo $this->form; ?>
</div>