<div>
    <nav class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                </button>
                <a class="navbar-brand" href="<?php echo $this->url(array('module' => '', 'controller' => '', 'action' => ''), null, true) ?>">Logo</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'index'), null, true) ?>">
                        <span class="glyphicon glyphicon-user"></span> Administrator </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-left">
                    <li><a href="#about">ABOUT</a></li>
                    <li><a href="#services">SERVICES</a></li>
                    <li><a href="http://localhost/MissionSmiles/public/#contact">CONTACT</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div class="jumbotron3">
    <br>
    <div>
        <img src="http://aceinstitutions.com/User/img/stdLogin.png" >
    </div>
    <p></p>
    <?php echo $this->form; ?>
    <h4>New User Register </h4>
    <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'index'), null, true) ?>">
            Here</a>
</div>