<div>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <img border="0" src="http://www.asthmamd.org/images/icon_user_1.png" width="90" height="50">
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="dropdown" >
                        <a class="dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'test'));?>">My Profile
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'preview'));?>?id=<?php $this->id;?>"><span class="glyphicon glyphicon-edit"> Edit Profile</span> </a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'test'));?>"><span class="glyphicon glyphicon-check"> View Profile </span></a></li>
                        </ul>
                    </li>
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">Contact Details</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=""><?php  echo " Hello, ".$this->result; ?></a></li>
                    <li class="dropdown" >
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-cog"> Setting <span class="caret"></span></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'logout'));?>"><span class="glyphicon glyphicon-log-out"> Logout </span></a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'change-password'));?>"><span class="glyphicon glyphicon-edit"> Change Password</span></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div>
    <h1><?php  echo "Hii ".$this->result. ","; ?></h1>
    <h2>Update Your Profile Here.... </h2>
    <hr>
    <?php
        $this->form = new User_Form_EditUser();
        $this->form->setDefaults($this->data);
        echo $this->form;
        if (!empty($this->message)){ 
    ?>
        <h4 class="alert alert-success"> <?php echo $this->message; ?> </h4>
   <?php   
        }
    ?>
</div>