<div>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="<?php echo $this->url(array('module' => '', 'controller' => '', 'action' => ''), null, true) ?>">
                    <img src="http://mymoneykart.com/images/Home.png" width="70" height="50">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'about'), null, true) ?>">About</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'projects'), null, true) ?>">Our Team</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'contacts'), null, true) ?>">Contact Us</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'login'), null, true) ?>">
                        <span class="glyphicon glyphicon-log-in"></span> Login </a></li>

                    <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'index'), null, true) ?>">
                        <span class="glyphicon glyphicon-user"></span> Register </a></li>

                    <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'index'), null, true) ?>">
                        <span class="glyphicon glyphicon-user"></span> Administrator </a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>  
<div class="row">
    <div class="col-md-3">
        
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
        <img class="img-rounded" src="https://lh3.googleusercontent.com/-RBvgk8Jjj0A/V_OXvyw6jpI/AAAAAAAAAWE/HAGSRZ8hS-we101GOHkQZvoNFOG1O0dGgCL0B/h823/B612_20160723_173654-1-1.jpg" width="70%" />
        <br></br>
        <br>Developed By : Vaishali Lodhi</br>
        <br>Designed By : Vaishali Lodhi</br>
        <br><a href="https://plus.google.com/+VaishaliLodhi">Get In Touch</a> with Vaishali</br>
    </div>
    <div class="col-md-3">
        
    </div>
</div>