<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
    <nav class="navbar navbar-fixed-top ">
        <div class="container">
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'login'), null, true) ?>">
                            <span class="glyphicon glyphicon-user"></span> My Account 
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-left">
                    <li><a class="navbar-brand" href="<?php echo $this->url(array('module' => '', 'controller' => '', 'action' => ''), null, true) ?>">Home</a></li>
                    <li><a href="#about">ABOUT</a></li>
                    <li><a href="#activity">SERVICES</a></li>
                    <li><a href="#contact">CONTACT</a></li>
                 </ul>
            </div>
        </div>
    </nav>
    <div class="jumbotron text-center">
        <div style="background: #FFFF99;margin-left: 20px;margin-right: 26px;border-radius: 10px 10px 0px 0px;">
            <a href="http://localhost/MissionSmiles/public/#contact">
                <marquee style="color: #f00;font-size: 24px;letter-spacing: 2px;max-width: 100%;font-weight: bold;" behavior="alternate">
                    *** ADMISSION OPEN ! Click here to contact us***
                </marquee>
            </a>
        </div>
    </div>
    <!-- Container (About Section) -->
    <div id="about" class="container-fluid">
        <div class="row">
            <div class="col-sm-1 center">
            </div>
            <div class="col-sm-7">
                <h2>About D.N. Public School</h2><br>
                <h4>D.N. Public School Barela attempt to redefine your ward's future with knowledge and confidence by imparting education with the best teaching practices, We prepare children to become confident and responsible Indians.</h4><br>
                <p>D.N. Public School Barela was conceptualized in the year 2017 the "Devki Narayan Educational And Welfare Society" runs it. It is a co-ed English medium senior secondary school. It conducts classes from primary to senior secondary level.
                    The school is committed to provide every child best possible learning atmosphere. Our motto is "service before self".
                    Our school has a friendly atmosphere. We welcome every child as our family member.
                    Our aim is to prepare our students to be truly global citizens...</p>
                <br><button class="btn btn-default btn-lg">Get in Touch</button>
            </div>
            <div class="col-sm-4 center">
                <p></p>
                <img src="images/D-N-school barela.jpg" width="70%">
            </div>
        </div>
    </div>

    <div class="container-fluid text-center bg-grey">
        <h2>What our customers say</h2> 
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner bg-grey" role="listbox" >
                <div class="item active">
                    <h4>"This foundation is the best. I am so happy with the result!"<br><span style="font-style:normal;">John Doe, Salesman, Rep Inc</span></h4>
                </div>
                <div class="item">
                    <h4>"One word... WOW!!"<br><span style="font-style:normal;">John Doe, Salesman, Rep Inc</span></h4>
                </div>
                <div class="item">
                    <h4>"Could I... BE any more happy with this company?"<br><span style="font-style:normal;">Chandler Bing, Actor, FriendsAlot</span></h4>
                </div>
            </div>
             <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-globe logo slideanim"></span>
            </div>
            <div class="col-sm-8">
                <h2>Our Values</h2><br>
                <h4><strong>MISSION:</strong> Our mission lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h4><br>
                <p><strong>VISION:</strong> This means that we serve where's willingly, graciously and selflessly. We should not expect anything in return for our service because there is greater pleasure in giving than in receiving. By serving others we serve God. We are great reservoir of creature minds and planners. We want to take out school to a higher zenith. Its main motto is to deal with moral ethics with self perseverance and zeal to excel with the qualities required to meet the challenges of modern society. The School will be in benediction with everyone’s support and cooperation to achieve the sky of limit.</p>
            </div>
        </div>
    </div>

    <!-- Container (Services Section) -->
    <div id="activity" class="container-fluid text-center bg-grey">
        <h2><u>ACTIVITIES</u></h2>
        <br>
        <div class="row slideanim">
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-picture logo-small"></span>
                <h4>Gallery</h4>
                <p>We looks..</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-heart logo-small"></span>
                <h4>LOVE</h4>
                <p>We love, We care..</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-lock logo-small"></span>
                <h4>JOB DONE</h4>
                <p>Lorem ipsum dolor sit amet..</p>
            </div>
        </div>
        <br><br>
        <div class="row slideanim ">
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-leaf logo-small"></span>
                <h4>GREEN</h4>
                 <p>Lorem ipsum dolor sit amet..</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-certificate logo-small"></span>
                <h4>CERTIFIED</h4>
                <p>Certified by M.P.B.S.E.</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-download-alt logo-small"></span>
                <h4 style="color:#303030;">DOWNLOADS</h4>
                <p>Click here to download Registration form ..</p>
            </div>
        </div>
    </div>
    
    <!-- Container -->
    <div class="row text-center slideanim container-fluid">
        <h2>What you say?</h2>
        <div class="col-sm-4">
            <div class="thumbnail">
                <img src="http://indiannationalarmy.com/images/edu2.jpg" width="400" height="300">
            </div>
        </div>
        <div class="col-sm-4">
            <div class="thumbnail">
                <img src="http://us.123rf.com/450wm/bestdesign36/bestdesign361504/bestdesign36150401720/39232849-concept-or-conceptual-education-abstract-word-cloud-white-background-metaphor-to-child-family-school.jpg" width="400" height="300">
            </div>
        </div>
        <div class="col-sm-4">
            <div class="thumbnail">
                <img src="http://indiannationalarmy.com/images/edu3.jpg" width="400" height="300">
            </div>
        </div>
    </div><br>

    <!-- Container (Contact Section) -->
    <div id="contact" class="container-fluid bg-grey">
        <h2 class="text-center">CONTACT US</h2>
        <div class="row">
            <div class="col-sm-5">
                <p>Contact us and we'll get back to you within 24 hours.</p>
                <p><span class="glyphicon glyphicon-map-marker"></span> Jabalpur, Madhya Pradesh, India</p>
                <p><span class="glyphicon glyphicon-phone-alt"></span> +0761-289060</p>
                <p><span class="glyphicon glyphicon-phone"></span> 9589289831, 9770868664</p>
                <p><span class="glyphicon glyphicon-envelope"></span> deepakkush94@gmail.com</p>
                <p><span class="glyphicon glyphicon-thumbs-up"></span></p>
            </div>
            <div class="col-sm-7 slideanim">
                <div class="row">
                    <div class="col-sm-6 form-group">
                        <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
                    </div>
                    <div class="col-sm-6 form-group">
                        <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
                    </div>
                </div>
                <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
                <div class="row">
                    <div class="col-sm-12 form-group">
                        <button class="btn btn-default pull-right" type="submit">Send</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--
    <div id="googleMap" style="height:400px;width:100%;"></div>Add Google Maps 
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
    var myCenter = new google.maps.LatLng(41.878114, -87.629798);

    function initialize() {
    var mapProp = {
      center:myCenter,
      zoom:12,
      scrollwheel:false,
      draggable:false,
      mapTypeId:google.maps.MapTypeId.ROADMAP
      };

    var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);

    var marker = new google.maps.Marker({
      position:myCenter,
      });

    marker.setMap(map);
    }

    google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    -->
    <footer class="container-fluid text-center">
      <a href="#myPage" title="To Top">
        <span class="glyphicon glyphicon-chevron-up"></span>
      </a>
      <p>Developed By <a href="https://plus.google.com/u/1/+VaishaliLodhi" title="Visit w3schools">Vaishali Lodhi</a> Software Engineer</p>
    </footer>

    <script>
    $(document).ready(function(){
      // Add smooth scrolling to all links in navbar + footer link
      $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
        // Make sure this.hash has a value before overriding default behavior
        if (this.hash !== "") {
          // Prevent default anchor click behavior
          event.preventDefault();

          // Store hash
          var hash = this.hash;

          // Using jQuery's animate() method to add smooth page scroll
          // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
          $('html, body').animate({
            scrollTop: $(hash).offset().top
          }, 900, function(){

            // Add hash (#) to URL when done scrolling (default click behavior)
            window.location.hash = hash;
          });
        } // End if
      });

      $(window).scroll(function() {
        $(".slideanim").each(function(){
          var pos = $(this).offset().top;

          var winTop = $(window).scrollTop();
            if (pos < winTop + 600) {
              $(this).addClass("slide");
            }
        });
      });
    })
    </script>    
</body>