<div>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <img border="0" src="http://www.asthmamd.org/images/icon_user_1.png" width="90" height="50">
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'test'));?>">User's Record</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'view'));?>">My Profile</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'contact'));?>">Contact Details</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=""><?php  echo " Hello, ".$this->result; ?></a></li>
                    <li class="dropdown" class="active">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-cog"> Setting <span class="caret"></span></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'logout'));?>"><span class="glyphicon glyphicon-log-out"> Logout </span></a></li>
                            <li><a href="#"><span class="glyphicon glyphicon-edit"> Change Password</span></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div>
    <img src="http://logos.textgiraffe.com/logos/logo-name/Admin-designstyle-boots-m.png" >
</div>
<div >
    <table class="table table-hover" >
        <tr>
            <td> Registration Id </td>
            <td><?php echo $this->id; ?></td>
        </tr>
        <tr>
            <td> User Name </td>
            <td><?php echo $this->uname; ?></td>
        </tr>
    </table>
</div>